---
abstract: 'A simple web crawler for CSCI 3172 Assignment 1'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  HTTP::Headers: 0
  HTTP::Response: 0
  Module::Build: 0.3601
  Test::Mock::LWP::Dispatch: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-3172-Crawler
no_index:
  directory:
    - corpus
requires:
  Data::Printer: 0
  Data::Validate::URI: 0
  Getopt::Long: 0
  HTML::TokeParser::Simple: 0
  LWP::RobotUA: 0
  List::UtilsBy: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Pod::Usage: 0
  Time::HiRes: 0
  URI::WithBase: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/doherty/WWW-3172-Crawler.git
version: 0.001
